<?php

namespace QuizzBundle\Repository;

/**
 * QuestionDoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionDoneRepository extends \Doctrine\ORM\EntityRepository
{
}
