<?php

namespace QuizzBundle\Repository;

/**
 * QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function countByThemeAfter($theme_id, $private, $deleted, $offset)
    {
      $qb = $this->createQueryBuilder('a');

      $qb
        ->select('COUNT(a)')
        ->where('a.theme = :themeid')
        ->setParameter('themeid', $theme_id)
        ->andWhere('a.private = :private')
        ->andWhere('a.deleted = :deleted')
        ->setParameter('private', $private)  
        ->setParameter('deleted',   $deleted)  
        ->setFirstResult($offset)
      ;

      return $qb
        ->getQuery()
        ->getOneOrNullResult()
      ;
    }
}
