<?php

namespace QuizzBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getbetween($quizz_id, $date1, $date2)
    {
      $qb = $this->createQueryBuilder('a');

      $qb
        ->select('a.rate')
        ->where('a.quizz = :quizzid')
        ->setParameter('quizzid', $quizz_id)
        ->andWhere('a.date BETWEEN :start AND :end')
        ->setParameter('start', $date1)
        ->setParameter('end',   $date2)  
      ;

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
